# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\ZabbixClient\:
    resource: '../Classes/*'

  WapplerSystems\ZabbixClient\Command\LockCommand:
    tags:
      - name: 'console.command'
        command: 'zabbix_client:lock'
        # not required, defaults to false
        hidden: false

  WapplerSystems\ZabbixClient\Controller\ConfigurationController:
    public: true
